config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "static_pages#home"
  get "help" => "static_pages#help"
  get "about" => "static_pages#about"

  resources :users do
    resource :skill_users
      get "add_skills" => "skill_users#show"
    end
  namespace :admin do
    root "users#index"
    resources :users
    resources :skills
    resources :positions
    resources :teams
  end
  resources :skills, only: :index
  resources :projects, only: :index
end

app/models/position.rb
class Position < ActiveRecord::Base
  has_many :position_users, dependent: :destroy
  has_many :users, through: :position_users, foreign_key: "position_id",
    dependent: :destroy
end

app/controllers/admin/positions_controller.rb
class Admin::PositionsController < ApplicationController
  before_action :authenticate_user!
  before_action :admin_user
  before_action :set_position, except: [:index, :new, :create]
  
  def index
    @positions = Position.paginate page: params[:page], 
      per_page: Settings.index.page
  end

  def show
  end

  def new
    @position = Position.new
  end

  def create
    @position = Position.new position_params
    if @position.save
      flash[:success] = t "admin.position.create_suc" 
      redirect_to admin_position_path @position
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @position.update position_params
      flash[:info] = t "admin.position.update"
      redirect_to admin_position_path @position
    else
      render :edit
    end
  end

  def destroy
    if @position.destroy
      flash[:success] = t "admin.position.destroy"
    else
      flash[:fail] = t "admin.position.destroy_fail"
    end
    redirect_to admin_positions_path
  end

  private
  def set_position
    @position = Position.find params[:id]
  end

  def position_params
    params.require(:position).permit :name, :abbreviation
  end
end

app/views/admin/positions/_form.html.erb
<%= form_for [:admin, @position] do |f| %>
  <p>
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
    <%= f.label :abbreviation %>
    <%= f.text_field :abbreviation, class: "form-control" %>
  </p>
  <p>
    <%= f.submit :submit, class: "btn btn-primary col-md-12" %>
  </p>
<% end %>

app/views/admin/positions/_position.html.erb
<li>
  <div class= "col-md-3 col-md-offset-1">
    <%= link_to position.name, [:admin, position] %></div>
  <div class= "col-md-3 col-md-offset-5">
    <%= link_to t("admin.user.detail"), [:admin, position], class: "btn btn-primary" %>
    <%= link_to t("admin.user.edit"), [:edit, :admin, position], class: "btn btn-primary" %>
    <%= link_to t("admin.user.delete"), [:admin, position], data: {confirm: t("admin.user.confirm")}, 
      method: :delete, class: "btn btn-primary" %>
  </div>
</li>

app/views/admin/positions/edit.html.erb
<% provide :title, t("admin.position.edit") %>
<div class="row">
  <div class="box">
    <div class="col-lg-12">
      <hr>
      <h2 class="intro-text text-center">
        <strong><%= t "admin.position.edit" %></strong>
      </h2>
      <hr>
      <div>
        <%= render partial: "form" %>
      </div>
    </div>
  </div>
</div>

app/views/admin/positions/index.html.erb
<% provide :title, t("admin.position.all_position") %>
<div class="row">
  <div class="box">
    <div class="col-lg-12">
      <hr>
      <h2 class="intro-text text-center">
        <strong><%= t "admin.position.all_position" %></strong>
      </h2>
      <hr>
      <div><%= link_to t("admin.position.create"), new_admin_position_path,
        class: "edit-btn btn btn-primary col-md-4 col-md-offset-4" %></div>
      <ul class="col-lg-12">
        <div class="col-md-offset-9"><%= will_paginate %></div>
        <%= render partial: "position", collection: @positions %>
        <div class="col-md-offset-9"><%= will_paginate %></div>
      </ul>
    </div>
  </div>
</div>

app/views/admin/positions/new.html.erb
<% provide :title, t("admin.position.create") %>
<div class="row">
  <div class="box">
    <div class="col-lg-12">
      <hr>
      <h2 class="intro-text text-center">
        <strong><%= t "admin.position.create" %></strong>
      </h2>
      <hr>
      <div>
        <%= render "form" %>
      </div>
    </div>
  </div>
</div>

app/views/admin/positions/show.html.erb
<div class="row">
  <div class="box">
    <div class="col-lg-12">
      <hr>
      <h2 class="intro-text text-center">
        <strong><%= t "admin.position.show" %></strong>
      </h2>
      <hr>
      <div class="col-md-3 col-md-offset-1">
        <p><%= t("admin.position.name") + @position.name %></p>
        <p><%= t("admin.position.abbreviation") + @position.abbreviation %></p>
      </div>
    </div>
  </div>
</div>