config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "static_pages#home"
  get "help" => "static_pages#help"
  get "about" => "static_pages#about"

  resources :users do
    resource :skill_users
      get "add_skills" => "skill_users#show"
    end
  namespace :admin do
    root "users#index"
    resources :users
    resources :skills
    resources :positions
    resources :teams
  end
  resources :skills, only: :index
  resources :projects, only: :index
end

app/models/skill.rb
class Skill < ActiveRecord::Base
  has_many :skill_users, dependent: :destroy
  has_many :users, through: :skill_users, foreign_key: "skill_id"
end

app/controllers/admin/skills_controller.rb
class Admin::SkillsController < ApplicationController
  def new
    @skill = Skill.new
  end

  def create
    @skill = Skill.new skill_params
    if @skill.save
      flash[:success] = t "skill.createskillcomplete" 
      redirect_to skills_path
    else
      render "new"
    end
  end

  def edit
    @skill = Skill.find params[:id]
  end

  def update
    @skill = Skill.find params[:id]
    if @skill.update_attributes skill_params
      flash[:success] = t "skill.editskillcompl"
      redirect_to skills_path
    else
      render "edit"
    end
  end

  def destroy
    Skill.find(params[:id]).destroy
    flash[:success] = t "skill.delskillcompl"
    redirect_to skills_path
  end

  private 
  def skill_params
    params.require(:skill).permit :name 
  end
end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController
  def index
    @skills = Skill.paginate page: params[:page]
  end
  
  def show
    @skill = Skill.find params[:id]
  end
end

app/views/skills/_skill.html.erb
<div>
  <%= skill.name %>

  <%= link_to t("skill.editskill"), edit_admin_skill_path(skill)%>
  <%= link_to t("skill.delskill"), admin_skill_path(skill), method: :delete %>
</div>

app/views/skills/index.html.erb
<div>
  <% if can? :create, @skills %>
    <%= link_to t("skill.createskill"), new_admin_skill_path %>
  <% else %>
    <%= link_to t("skill.addskill"), root_path%>
  <% end %>
</div>
<div>
  <%= render partial: "skill", collection: @skills %>
</div>