config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "static_pages#home"
  get "help" => "static_pages#help"
  get "about" => "static_pages#about"

  resources :users do
    resource :skill_users
      get "add_skills" => "skill_users#show"
    end
  namespace :admin do
    root "users#index"
    resources :users
    resources :skills
    resources :positions
    resources :teams
  end
  resources :skills, only: :index
  resources :projects, only: :index
end

app/models/skill_user.rb
class SkillUser < ActiveRecord::Base
  belongs_to :user
  belongs_to :skill
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable

  has_many :team_users, dependent: :destroy
  has_many :teams, through: :team_users, foreign_key: "user_id",
    dependent: :destroy

  has_many :skill_users, dependent: :destroy
  has_many :skills, through: :skill_users, foreign_key: "user_id"

  has_one :leading_team, class_name: "Team", foreign_key: "leader_id"

  has_many :project_users, dependent: :destroy
  has_many :projects, through: :project_users, foreign_key: "user_id",
    dependent: :destroy
  
  has_many :position_users, dependent: :destroy
  has_many :positions, through: :position_users, foreign_key: "user_id",
    dependent: :destroy

  accepts_nested_attributes_for :position_users, allow_destroy: true
  accepts_nested_attributes_for :skill_users, allow_destroy: true

  validates :name, presence: true, uniqueness: true
  validates :email, presence: true

  scope :without_user, ->user{where.not id: user}
  scope :not_in_team, ->{where Settings.user.not_in_team}

  def is_admin?
    role == Settings.user.role.admin
  end
end

app/controllers/skill_users_controller.rb
class SkillUsersController < ApplicationController  
  def show
    @user = User.find params[:user_id]
    @skills = Skill.all
  end
end

app/views/skill_users/_skill.html.erb
<%= form_for @user do |p| %>
  <%= render "shared/error_messages", object: p.object %>
  <table class="table table-bordered">
    <%= p.collection_check_boxes :skill_ids, Skill.all, :id, :name do |b| %>
      <tr>
        <td><%= b.check_box %></td>
        <td><%= b.object.name %></td>
      </tr>
    <% end %>
  </table>
  <%= hidden_field_tag :flag, Settings.user.one %>
  <%= p.submit :add, class: "btn btn-primary" %>
<% end %>

app/views/skill_users/_skill_form.html.erb
<%= form_for @user do |f| %>
  <%= render "shared/error_messages", object: f.object %>
  <table class="table table-bordered">
    <tr>
      <th></th>
      <th><%= t "skill.name" %></th>
      <th><%= t "skill.level" %></th>
      <th><%= t "skill.year" %></th>
    </tr>
    <%= f.fields_for :skill_users do |builder| %>
      <tr>
        <td><%= builder.check_box :_destroy,
          {checked: @user.skills.include?(builder.object.skill)}, false, true %></td>
        <%= builder.hidden_field :skill_id %>
        <td><%= builder.object.skill.try(:name) %></td>
        <td><%= builder.select :level, Settings.user.level %></td>
        <td><%= builder.text_field :used_year %></td>
        <%= hidden_field_tag :flag, Settings.user.zero %>
      </tr>
    <% end %>
  </table>
  <%= f.submit :submit, class: "btn btn-primary" %>
<% end %>

app/views/skill_users/show.html.erb
<% provide :title, t("skill.addskill") %>
<h1><%= t "skill.addskill" %></h1>
<h3><%= link_to t("layouts.profile"), user_path(@user) %></h3>
<div class="row">
  <div class="col-md-6">
    <%= render "skill_form" %>
  </div>
  <div class="col-md-6">
    <%= render "skill" %>
  </div>
</div>